[package]
name = "cozy-chess"
version = "0.2.2"
authors = ["analog-hors <44050761+analog-hors@users.noreply.github.com>"]
edition = "2021"

license = "MIT"
description = "Rust Chess and Chess960 move generation library"
homepage = "https://github.com/analog-hors/cozy-chess/"
repository = "https://github.com/analog-hors/cozy-chess/"
keywords = ["chess"]
readme = "../README.md"

[dependencies]
cozy-chess-types = { path = "../types", version = "0.1.4" }
# lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[build-dependencies]
cozy-chess-types = { path = "../types", version = "0.1.4" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "perft"
harness = false

[[bench]]
name = "legals"
harness = false
